### Products Index
GET http://localhost:3000/products.json?category=Furniture
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NzkwMTExODZ9.0W0mG_UHcffoUYSlF6kSFTLQITASOXTGQQGrR4_jvYA

 
### Products Show
GET http://localhost:3000/products/2.json

### Products Create
POST http://localhost:3000/products.json
Content-Type: application/json

{
  "name": "Baseball bat",
  "price": 15,
  "description": "A wooden baseball bat",
  "supplier_id": 2,
  "inventory": 11,
  "url": "https://cdn11.bigcommerce.com/s-2hhnbofc/images/stencil/1280x1280/products/4588/19316/5__59702.1610657598.jpg?c=2"
}

### Products Create Post
POST http://localhost:3000/products.json

### Products Update
PATCH http://localhost:3000/products/2.json


### Product Delete
DELETE http://localhost:3000/products/3.json 



### Suppliers Index
GET http://localhost:3000/suppliers.json

### Suppliers Show
GET http://localhost:3000/suppliers/1.json 

### Suppliers Create
POST http://localhost:3000/suppliers.json 

### Suppliers Update
PATCH http://localhost:3000/suppliers/2.json 

### Suppliers Delete
DELETE http://localhost:3000/suppliers/2.json 

### Images Index
GET http://localhost:3000/images.json

### Images Show
GET http://localhost:3000/images/1.json

### Images Create
POST http://localhost:3000/images.json
Content-Type: application/json

{
  "url": "http://test.com/image/123.jpeg",
  "product_id": 2
}

### User Create
POST http://localhost:3000/users.json 
# Content-Type: application/json

# {
#   "name": "Karen L",
#   "email": "karenl@test.com",
#   "password": "password",
#   "password_confirmation": "password"
# }

### Session Create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "karenl@test.com",
  "password": "password"
}

### Order Index
GET http://localhost:3000/orders.json 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NzkwMDk5NjF9.nHjO-CpIn292x_4pGykISIg9KGGHLb3Fu6sa8-zbNek

### Order Show
GET http://localhost:3000/orders/1.json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2Nzg5MjQ2MDh9.FUcpPbaikDXQxZ-9j0_ZesM3jtk5hqJKATTCs1h2Ous

### Order Create
POST http://localhost:3000/orders.json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2Nzg5MjQ2MDh9.FUcpPbaikDXQxZ-9j0_ZesM3jtk5hqJKATTCs1h2Ous

{
  "product_id": 3,
  "quantity": 2
}

### CartedProducts Index
GET http://localhost:3000/cartedproducts.json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2Nzk0NDI4MTV9.YYeiYcxlpOuca-tHVGyj8JygOt8N27aNecIh7ZxlkZo

### CartedProduct Create
POST http://localhost:3000/cartedproducts.json 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NzkzMzE1Mzh9.yA1HtMENvpXUJ77J1hkl-iMqLPIypsdVPZLMzjPpyl4

{
  "product_id": 2,
  "quantity": 5,
}