### Products Index

GET http://localhost:3000/products

 
### Products Show
GET http://localhost:3000/products/:id

### Products Create
POST http://localhost:3000/products.json
Content-Type: application/json

{
  "name": "Yeti Mug",
  "price": 23,
  "image_url": "http://imghost.com/13556",
  "description": "Keeps liquids hot or cold"
}

### Products Create Post
POST http://localhost:3000/products.json

### Products Update
PATCH http://localhost:3000/products/1.json
Content-Type: application/json

{
  "name": "Crystal Skull"
}

### Product Delete
DELETE http://localhost:3000/products/8.json 
